### PR TITLE
Add duration

### PR DESCRIPTION
**Pull request by mikemccourt**
Starting this PR now, will also need to add suggestion changes.

### CODE REVIEW

**Comment by alexandraj777** [comment]
What was suggestion duration, again?

**Comment by mikemccourt** [comment]
From this doc: https://docs.google.com/document/d/1-bdM8hHl56_8Ilo7F7NUcMwd6IRfe_OpvoWdJauINkg/edit#.

TLDR, for cross-validation experiments, we're gonna change names:
folds -> suggestion_duration  (on the Experiment object)
fold -> reference  (on the Suggestion object)
fold_index -> progress_index  (on the Suggestion object)

Then the same terminology will be used for both cross-validation and early termination experiments, although the deprecated names will still be available, I think.  Or maybe they won't be, we'll have to decide on that, I guess.

**Comment by mikemccourt** [comment]
I'm going to start making the edits in https://github.com/sigopt/sigopt-api/pull/3117 to change the passing to the suggestion object, but I think everything else is done here.

**Comment by mikemccourt** [comment]
Yep, good call.  I have a couple more things to deal with on the server side and then we can merge this.

**Comment by pfhayes** [comment]
Going to put out 2.14.0 without this change since this deprecates some things

**Comment by pfhayes** [comment]
Nm, was 2.13.1

**Comment by mikemccourt** [comment]
Do whatever you need to, I'm still making the last few changes in the API.

**Comment by mikemccourt** [comment]
@benhsu75 This is ready to go unless you'd like to reconsider the name `suggestion_duration`.  Nothing is public until this goes out, and https://github.com/sigopt/sigopt-api/pull/3117 can be change to use whatever other names we want.  As this stands right now, nothing is on the path to being deprecated and the new ET content in no way interacts with the existing CV content.

**Comment by benhsu75** [comment]
You've thought more about the term for Early Termination than me, so if your choice is `suggestion_duration` that sounds good to me

**Comment by mikemccourt** [comment]
You're not the only one to have reservations about it, and the google doc never really had a firm conclusion.  I guess the point is that, if anyone has any significant discomfort with anything, I'd rather take a day, think about it, and make a decision that we can all get behind than just come up with something I like for no real reason other than I like it.

**Comment by mikemccourt** [comment]
With the merger of https://github.com/sigopt/sigopt-api/pull/3297 complete, we should now merge this and submit to pypi.

**Comment by mikemccourt** [comment]
Makes perfect sense.  We'll do it tomorrow.

**Comment by mikemccourt** [comment]
Will probably need to bump the version of this then.  I'll do that and then merge this in.

**Comment by mikemccourt** [comment]
This is merged in.  Not sure what our pypi release sequence is, though.

**Comment by pfhayes** [comment]
I'll release

**Comment by pfhayes** [comment]
2.14.0 has been pushed to Pypi

**Pull request merged**
