### PR TITLE
include sources for all installed packages

### PR DESCRIPTION
**Pull request by taylorjacklespriggs**
This downloads the source code for all installed alpine packages so they can be distributed in the container. Not sure if that's what we want.

### CODE REVIEW

**Comment by taylorjacklespriggs** [comment]
This image is ~750MB! (vs about 100MB for without sources)

**Comment by dwanderson-intel** [comment]
yeah... im guessing thats why they dont want to include them in alpine normally. We can check if it's sufficient to include the source at some (other) downloadable location - I think people will rarely want it, so hosting it on S3 shouldn't be an issue.

**Comment by taylorjacklespriggs** [comment]
no longer required

**Comment by dwanderson-intel** [comment]
Thanks again for digging in in case we did need it. I'm sure stuff like this will continue to come up as we increase our container usage, so I still think it was a worthwhile exercise.

**Pull request closed without merging**
