### PR TITLE
Parse task info from API

### PR DESCRIPTION
**Pull request by mikemccourt**
This will allow customers to access task information.  Will need to wait for requisite merger on API side.

### CODE REVIEW

**Comment by mikemccourt** [comment]
@alexandraj777 I'm not sure how we want to change the version number for this.  It's relatively small.  Do we have a desired principle regarding this?

**Comment by alexandraj777** [comment]
Yup! Ping me when this is merged and I can change the version number and deploy (Patrick and I are, I believe, the only ones with pypi creds ATM).

Version number changes are based on: https://semver.org/. Usually, adding a field is a "minor" version change.

**Comment by alexandraj777** [comment]
test lgtm

**Comment by alexandraj777** [comment]
Thanks for waiting on this! I've fixed up a merge conflict and I'll merge and release today

**Pull request merged**
