### PR TITLE
Convert test from EggHolder to Franke

### PR DESCRIPTION
**Pull request by mikemccourt**
Couple comments and change domain.  Not as short as the EggHolder
function, but still okay.  @alexandraj777

### CODE REVIEW

**Comment by mikemccourt** [comment]
@pfhayes @alexandraj777 Why did this travis test fail?

**Comment by pfhayes** [comment]
Is this the issue?

$ make lint
moe/moe/optimal_learning/python/python_version/log_likelihood.py:19:1: F401
'NullOptimizer' imported but unused

**Comment by mikemccourt** [comment]
I'm looking at the sigopt-python repo.

**Comment by pfhayes** [comment]
Gotcha - looks like an intermitten failure. I think you are fine to push

**Pull request merged**
