### PR TITLE
Proposal: Remove training set metrics

### PR DESCRIPTION
**Pull request by harvey-intel**
I feel like all the training set metrics are cluttering up the web.

### CODE REVIEW

**Comment by ericlee0803** [comment]
Cluttering up in the sense of checkpointing, or the bar plots? 

An alternative is to log them but not display them. I suppose that takes even more web work (and possibly a change to the metric logging as well).

**Comment by harvey-intel** [comment]
Bar plot mostly, but also the Metrics subsection. We don't log checkpoints for training set (unless user put training set in `evals`).

**Comment by ericlee0803** [comment]
Hmmm... okay this is fine with me but can we run this by Eddie tomorrow.

**Review by ericlee0803 — APPROVED** [review]
Looks good to me. Thank you again!!

**Pull request merged**
