### PR TITLE
update controller

### PR DESCRIPTION
**Pull request by taylorjacklespriggs**
I built the container but I am not able to upload it with my current connection.

### CODE REVIEW

**Review by dwanderson-intel — APPROVED** [review]
LGTM

confirming - there are no changes to the alpine libraries, just cleaning up / being more precise about them?

And pypng is not a new dependency, just special-cased for install issues?

Takwaway being - nothing net-new 3rd party has been added, right?

**Comment by taylorjacklespriggs** [comment]
You added `krb5-libs` in a different PR, not sure if that was addressed by the last ospdt mtg

**Comment by taylorjacklespriggs** [comment]
otherwise I'm confident no dependencies have changed since the last release

**Comment by dwanderson-intel** [comment]
Great - krb5 was in the last review, so we're all set there. Thanks!

**Pull request merged**
