### PR TITLE
Multicriteria

### PR DESCRIPTION
**Pull request by oliviakim95**
@pfhayes @alexandraj777

### CODE REVIEW

**Comment by pfhayes** [comment]
can you add DeprecatedField annotations to the old fields?

**Comment by pfhayes** [comment]
looks good! let's wait until all the code and docs are live before we push this

**Comment by mikemccourt** [comment]
So, because eval uses prod sigopt, would this need to be live to run?  Or
no, since we're hoping the old behavior would still be acceptable?

**Comment by pfhayes** [comment]
Yeah, using the old behaviour should be fine - we want to make sure that we
didn't break behaviour for anyone using the old client, so eval is a good
candidate for that

**Pull request merged**
