### PR TITLE
bump version to 4.2.0

### PR DESCRIPTION
**Pull request by oliviakim95**
- metric thresholds
- metric minimization

### CODE REVIEW

**Comment by alexandraj777** [comment]
Released from this branch!

**Comment by alexandraj777** [comment]
@sarthfrey can you confirm that your changes also went out with 4.2.0? I deployed from this branch, rather than from master

**Comment by sarthfrey** [comment]
Working like a charm! created thresholds with version `4.2.0`

https://app.staging.sigopt.com/experiment/30883/properties

**Comment by alexandraj777** [comment]
Cool! @oliviakim95 @sarthfrey who's owning updating the client in the sigopt api codebase?

**Comment by oliviakim95** [comment]
> Cool! @oliviakim95 @sarthfrey who's owning updating the client in the sigopt api codebase?

I can do that

**Pull request merged**
